import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/NavBar";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "next-auth/react";
import Provider from "./Provider";
const inter = Inter({ subsets: ["latin"] });
// export const metadata: Metadata = {
//   title: "Homepage - blog app",
//   description: "Generated by create next app",
// };
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" >


      <body className={inter.className}>
        <Provider>
          <NavBar />

          <div className="">

            {/* <SessionProvider> */}
            {children}
            <Toaster />

            {/* </SessionProvider> */}
          </div>
        </Provider>
      </body>
    </html>
  );
}
